apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-doc-api
  labels:
    app: banking-doc-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-doc-api
  template:
    metadata:
      labels:
        app: banking-doc-api
    spec:
      containers:
      - name: banking-doc-api
        image: banking-doc-mlops:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://banking-mlflow-service:5000"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-mlflow
  labels:
    app: banking-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-mlflow
  template:
    metadata:
      labels:
        app: banking-mlflow
    spec:
      containers:
      - name: banking-mlflow
        image: python:3.9-slim
        command: ["bash", "-c"]
        args:
          - "pip install mlflow --quiet && mlflow server --host 0.0.0.0 --port 5000"
        ports:
        - containerPort: 5000
