apiVersion: v1
kind: Service
metadata:
  name: banking-doc-api-service
spec:
  type: LoadBalancer
  selector:
    app: banking-doc-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: banking-mlflow-service
spec:
  type: ClusterIP
  selector:
    app: banking-mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
